apiVersion: v2
name: squid
description: A Helm chart for Squid caching proxy
deprecated: false
type: application
version: 0.4.0
appVersion: "6.10"
kubeVersion: ">=1.21.0-0"
keywords:
  - squid-cache
  - squid
  - proxy
  - forward-proxy
  - cache
home: https://www.squid-cache.org/
sources:
  - https://www.squid-cache.org/
  - https://github.com/younsl/younsl.github.io
  - https://younsl.github.io/charts/
maintainers:
  - name: younsl
    email: cysl@kakao.com
    url: https://github.com/younsl
