apiVersion: v2
name: squid
description: A Helm chart for Squid caching proxy
deprecated: false
type: application
version: 0.7.0
appVersion: "6.13"
kubeVersion: ">=1.21.0-0"
keywords:
  - squid-cache
  - squid
  - proxy
  - forward-proxy
  - cache
home: https://www.squid-cache.org/
sources:
  - https://www.squid-cache.org/
  - https://hub.docker.com/r/ubuntu/squid
  - https://github.com/younsl/charts
maintainers:
  - name: younsl
    email: cysl@kakao.com
    url: https://github.com/younsl
