apiVersion: v2
name: rbac
description: Helm chart to define RBAC resources in the gitops way
deprecated: false
keywords:
- cluster-security
- rbac
- clusterRole
- clusterRoleBinding
- role
- roleBinding
type: application
version: 0.2.1
appVersion: 0.2.1
home: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
sources:
  - https://github.com/younsl/younsl.github.io
  - https://younsl.github.io/charts/
maintainers:
- name: younsl
  email: cysl@kakao.com
  url: https://github.com/younsl
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/younsl/charts
