{{- range $name, $vac := .Values.volumeAttributeClasses }}
{{- if $vac.enabled }}
---
apiVersion: storage.k8s.io/v1beta1
kind: VolumeAttributesClass
metadata:
  name: {{ $name }}
  {{- if or $vac.annotations $.Values.globalAnnotations }}
  annotations:
    {{- with $.Values.globalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $vac.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if or $vac.labels $.Values.globalLabels }}
  labels:
    {{- include "storage-class.labels" $ | nindent 4 }}
    {{- with $.Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $vac.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
driverName: {{ $vac.driverName }}
{{- with $vac.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
