# Test with multiple StorageClasses enabled
# This tests the chart with various storage configurations

globalAnnotations:
  test.example.com/managed-by: helm

globalLabels:
  environment: test

defaultStorageClass: gp3

storageClasses:
  gp3:
    enabled: true
    annotations:
      storageclass.kubernetes.io/description: "General purpose SSD storage"
    labels:
      performance: standard
    provisioner: ebs.csi.aws.com
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    parameters:
      type: gp3
      iops: "3000"
      throughput: "125"

  gp3-encrypted:
    enabled: true
    annotations:
      storageclass.kubernetes.io/description: "Encrypted general purpose SSD storage"
    labels:
      performance: standard
      security: encrypted
    provisioner: ebs.csi.aws.com
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    parameters:
      type: gp3
      encrypted: "true"
      iops: "3000"
      throughput: "125"

  io2:
    enabled: true
    annotations:
      storageclass.kubernetes.io/description: "High performance IOPS SSD storage"
    labels:
      performance: high
    provisioner: ebs.csi.aws.com
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    parameters:
      type: io2
      iops: "10000"
    allowedTopologies:
    - matchLabelExpressions:
      - key: topology.ebs.csi.aws.com/zone
        values:
          - us-east-1a
          - us-east-1b

  st1:
    enabled: true
    annotations:
      storageclass.kubernetes.io/description: "Throughput optimized HDD storage"
    labels:
      performance: throughput-optimized
      cost: low
    provisioner: ebs.csi.aws.com
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: false
    parameters:
      type: st1
    mountOptions:
      - debug
