{{- if .Values.serviceAccounts.enabled }}
{{- range $name, $serviceAccount := .Values.serviceAccounts.accounts }}
{{- if or (not (hasKey $serviceAccount "enabled")) $serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "argo-workflows-templates.labels" $ | nindent 4 }}
    {{- with $serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if hasKey $serviceAccount "automountServiceAccountToken" }}
automountServiceAccountToken: {{ $serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- with $serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $serviceAccount.secrets }}
secrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}