name: Update Chart Catalog

on:
  push:
    branches:
      - main
    paths:
      - 'charts/*/Chart.yaml'
      - '.github/scripts/update-chart-catalog.sh'
  workflow_dispatch:

jobs:
  update-catalog:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install yq
        uses: mikefarah/yq@v4.47.2

      - name: Update chart catalog
        run: |
          bash .github/scripts/update-chart-catalog.sh

      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --exit-code docs/chart-catalog.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs(ci): Update chart catalog'
          title: 'docs(ci): Update chart catalog'
          body: |
            ## Summary
            This PR automatically updates the chart catalog documentation based on changes to Chart.yaml files.

            ## Changes
            - Updated `docs/chart-catalog.md` with latest chart information
            - Synchronized chart versions, descriptions, and deprecation status

            ## Note
            This is an automated pull request generated by GitHub Actions workflow.
          branch: update-chart-catalog-${{ github.run_number }}
          delete-branch: true
          labels: |
            documentation
            automated
          assignees: ${{ github.repository_owner }}
          reviewers: ${{ github.repository_owner }}
