# Test fullnameOverride functionality
# This tests the fullname helper function behavior

fullnameOverride: "my-custom-rbac"

global:
  commonLabels:
    environment: test
    team: platform

clusterRoles:
  admin-reader:
    enabled: true
    labels:
      test-type: fullname-override
    rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "list", "watch"]

clusterRoleBindings:
  admin-reader:
    enabled: true
    labels:
      test-type: fullname-override
    roleRef:
      kind: ClusterRole
      name: admin-reader
    subjects:
      kind: Group
      name: platform-admins

# Using 'default' namespace for CI testing since it always exists in Kind clusters
# In production, you would typically use specific namespaces like 'development', 'staging', etc.
roles:
  default:
    namespace-admin:
      enabled: true
      labels:
        test-type: fullname-override
      rules:
      - apiGroups: ["", "apps", "extensions"]
        resources: ["*"]
        verbs: ["*"]

roleBindings:
  default:
    namespace-admin:
      enabled: true
      labels:
        test-type: fullname-override
      roleRef:
        kind: Role
        name: namespace-admin
      subjects:
      - kind: Group
        name: dev-team